import * as THREE from 'three';
import { fromFen, legalMoves, makeMove, undoMove, result, san, squareIndex, squareName, toFen } from './rules.js';

const $=s=>document.querySelector(s), stage=$('#stage'), scene=new THREE.Scene();
scene.background=new THREE.Color('#080b10');
const camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,120);camera.position.set(0,8.7,11.5);
const topCamera=new THREE.OrthographicCamera(-5.5,5.5,5.5,-5.5,.1,120);topCamera.position.set(0,26,0);topCamera.up.set(0,0,-1);topCamera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({canvas:stage,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;
const ambient=new THREE.HemisphereLight('#e0f2f0','#181618',1.45);scene.add(ambient);
const key=new THREE.DirectionalLight('#ffedcf',2.45);key.position.set(-5,11,7);key.castShadow=true;key.shadow.mapSize.set(1536,1536);key.shadow.camera.left=-8;key.shadow.camera.right=8;key.shadow.camera.top=8;key.shadow.camera.bottom=-8;key.shadow.bias=-.00035;scene.add(key);
const fill=new THREE.PointLight('#73e6dc',22,15,2);fill.position.set(5,3.2,1);scene.add(fill);const rim=new THREE.PointLight('#a789ff',30,16,2);rim.position.set(-4,3,-5);scene.add(rim);
function createEnvironment(){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,256);g.addColorStop(0,'#9fa9a0');g.addColorStop(.22,'#56615a');g.addColorStop(.5,'#191f20');g.addColorStop(1,'#808378');x.fillStyle=g;x.fillRect(0,0,512,256);for(let i=0;i<8;i++){x.fillStyle=`rgba(${i%2?'158,231,218':'236,203,145'},${i%2?.08:.07})`;x.fillRect(i*75,25,35,110);}const tex=new THREE.CanvasTexture(c);tex.mapping=THREE.EquirectangularReflectionMapping;scene.environment=tex;}
createEnvironment();
const floor=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshPhysicalMaterial({color:'#090d0d',roughness:.3,metalness:.24,clearcoat:.32,clearcoatRoughness:.32}));floor.rotation.x=-Math.PI/2;floor.position.y=-.34;floor.receiveShadow=true;scene.add(floor);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=256;const shadowContext=shadowCanvas.getContext('2d'),shadowGradient=shadowContext.createRadialGradient(128,128,26,128,128,126);shadowGradient.addColorStop(0,'rgba(0,0,0,.52)');shadowGradient.addColorStop(.58,'rgba(0,0,0,.34)');shadowGradient.addColorStop(1,'rgba(0,0,0,0)');shadowContext.fillStyle=shadowGradient;shadowContext.fillRect(0,0,256,256);const shadowTexture=new THREE.CanvasTexture(shadowCanvas);const tableShadow=new THREE.Mesh(new THREE.PlaneGeometry(15.6,15.6),new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false}));tableShadow.rotation.x=-Math.PI/2;tableShadow.position.set(0,-.332,0);scene.add(tableShadow);
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(5.9,6.25,.26,96),new THREE.MeshPhysicalMaterial({color:'#34271d',metalness:.32,roughness:.3,clearcoat:.65}));pedestal.position.y=-.2;pedestal.receiveShadow=true;pedestal.castShadow=true;scene.add(pedestal);
const tabletopEdge=new THREE.Mesh(new THREE.CylinderGeometry(6.34,6.48,.16,96),new THREE.MeshStandardMaterial({color:'#38291f',metalness:.14,roughness:.4}));tabletopEdge.position.y=-.07;tabletopEdge.receiveShadow=true;tabletopEdge.castShadow=true;scene.add(tabletopEdge);
const tableTop=new THREE.Mesh(new THREE.CylinderGeometry(6.34,6.34,.035,96),new THREE.MeshStandardMaterial({color:'#483528',metalness:.12,roughness:.42}));tableTop.position.y=.018;tableTop.receiveShadow=true;scene.add(tableTop);
const tableInlay=new THREE.Mesh(new THREE.TorusGeometry(6.25,.025,6,96),new THREE.MeshStandardMaterial({color:'#b8965f',metalness:.7,roughness:.26}));tableInlay.rotation.x=Math.PI/2;tableInlay.position.y=.038;scene.add(tableInlay);
const roomDecor=new THREE.Group();scene.add(roomDecor);
const wallMat=new THREE.MeshStandardMaterial({color:'#111b1b',roughness:.88,metalness:.06}),panelMat=new THREE.MeshStandardMaterial({color:'#1b2928',roughness:.8}),darkWood=new THREE.MeshStandardMaterial({color:'#30251d',roughness:.66}),warmGlow=new THREE.MeshBasicMaterial({color:'#d5a66c'}),tealGlow=new THREE.MeshBasicMaterial({color:'#64bcb2'}),shelfBooks=['#52635b','#66513e','#354a4d','#786445'].map(color=>new THREE.MeshStandardMaterial({color,roughness:.9}));
function roomBox(parent,material,w,h,d,x,y,z){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
roomBox(roomDecor,wallMat,30,11,.35,0,5.1,-10.4);
for(let i=0;i<9;i++)roomBox(roomDecor,panelMat,.045,8.2,.08,-13.2+i*3.3,5.1,-10.17);
for(const side of [-1,1]){const x=side*8.9;roomBox(roomDecor,darkWood,3.35,5.4,.72,x,2.7,-9.55);for(const y of [1.25,2.55,3.85,5.1]){roomBox(roomDecor,panelMat,3.18,.11,.82,x,y,-9.05);for(let i=0;i<5;i++){const h=.65+(i%3)*.13;const book=roomBox(roomDecor,shelfBooks[(i+Math.round(y*10))%shelfBooks.length],.28,h,.4,x-1.25+i*.61,y+.1+h/2,-9.13);book.rotation.z=(i%2?-.04:.035);}}}
// A small pair of practical lights and candle silhouettes sit behind the board.
for(const [x,color,material] of [[-5.9,'#dda971',warmGlow],[5.9,'#66c5bb',tealGlow]]){roomBox(roomDecor,darkWood,.16,2.05,.16,x,1.03,-8.65);roomBox(roomDecor,material,.8,.12,.54,x,2.12,-8.65);const glow=new THREE.PointLight(color,8,8,2);glow.position.set(x,2.15,-7.9);roomDecor.add(glow);}
for(const x of [-7.4,7.4]){const candle=new THREE.Mesh(new THREE.CylinderGeometry(.12,.15,.68,8),new THREE.MeshStandardMaterial({color:'#c7b496',roughness:.74}));candle.position.set(x,.34,-7.8);roomDecor.add(candle);const flame=new THREE.Mesh(new THREE.ConeGeometry(.075,.22,6),warmGlow);flame.position.set(x,.78,-7.8);roomDecor.add(flame);}
const loungeFog=new THREE.FogExp2('#111817',.012);scene.fog=loungeFog;
const dustCount=76,dustPositions=new Float32Array(dustCount*3),dustDrift=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){dustPositions[i*3]=(Math.random()-.5)*23;dustPositions[i*3+1]=.35+Math.random()*8;dustPositions[i*3+2]=(Math.random()-.5)*20-1;dustDrift[i*3]=(Math.random()-.5)*.12;dustDrift[i*3+1]=.025+Math.random()*.045;dustDrift[i*3+2]=(Math.random()-.5)*.1;}const dustGeometry=new THREE.BufferGeometry();dustGeometry.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({color:'#c8c4a9',size:.045,transparent:true,opacity:.22,depthWrite:false,sizeAttenuation:true}));roomDecor.add(dust);
const boardRoot=new THREE.Group();scene.add(boardRoot);
const boardBase=new THREE.Mesh(new THREE.BoxGeometry(8.82,.42,8.82),new THREE.MeshPhysicalMaterial({color:'#30241b',roughness:.28,metalness:.1,clearcoat:.7,clearcoatRoughness:.2}));boardBase.position.y=.12;boardBase.castShadow=true;boardBase.receiveShadow=true;boardRoot.add(boardBase);
const trim=new THREE.Mesh(new THREE.BoxGeometry(8.92,.12,8.92),new THREE.MeshPhysicalMaterial({color:'#ba9b64',roughness:.28,metalness:.67,clearcoat:.8}));trim.position.y=.22;boardRoot.add(trim);
const tileRoot=new THREE.Group();boardRoot.add(tileRoot);const squareMeshes=[],targetMeshes=[],captureMeshes=[],checkMeshes=[];
let neon=false;
const materials={light:new THREE.MeshPhysicalMaterial({color:'#e8dec7',roughness:.26,metalness:.05,clearcoat:.75,clearcoatRoughness:.18}),dark:new THREE.MeshPhysicalMaterial({color:'#403b33',roughness:.28,metalness:.07,clearcoat:.7,clearcoatRoughness:.2}),white:new THREE.MeshPhysicalMaterial({color:'#e8dfca',roughness:.19,metalness:.22,clearcoat:1,clearcoatRoughness:.12}),black:new THREE.MeshPhysicalMaterial({color:'#171e22',roughness:.17,metalness:.55,clearcoat:1,clearcoatRoughness:.1}),gold:new THREE.MeshPhysicalMaterial({color:'#c6a365',roughness:.21,metalness:.78,clearcoat:.8}),ivoryAccent:new THREE.MeshPhysicalMaterial({color:'#fff0cf',roughness:.22,metalness:.38}),blueAccent:new THREE.MeshPhysicalMaterial({color:'#638f8c',roughness:.22,metalness:.48,emissive:'#102522',emissiveIntensity:.14}),neonLight:new THREE.MeshPhysicalMaterial({color:'#b3d7c5',roughness:.18,metalness:.12,clearcoat:1}),neonDark:new THREE.MeshPhysicalMaterial({color:'#12272b',roughness:.2,metalness:.5,clearcoat:1})};
const squareGeo=new THREE.BoxGeometry(1,.11,1);const squareEdgeGeo=new THREE.BoxGeometry(.96,.125,.96);
const coordinateLabels={w:[],b:[]};
function addLabel(text,x,z,rotation=0,color='w'){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.clearRect(0,0,128,64);ctx.font='600 31px Georgia';ctx.fillStyle='#d9c79e';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,64,34);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(.48,.24),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.rotation.z=rotation;m.position.set(x,.456,z);m.userData.orientation=color;boardRoot.add(m);coordinateLabels[color].push(m);return m;}
for(let r=0;r<8;r++)for(let c=0;c<8;c++){const idx=r*8+c,sq=new THREE.Group(),isLight=(r+c)%2===0;const tile=new THREE.Mesh(squareGeo,(neon?(isLight?materials.neonLight:materials.neonDark):(isLight?materials.light:materials.dark)).clone());tile.position.y=.39;tile.receiveShadow=true;tile.castShadow=true;sq.add(tile);sq.position.set(c-3.5,0,r-3.5);tileRoot.add(sq);squareMeshes[idx]=sq;const dot=new THREE.Mesh(new THREE.CircleGeometry(.11,24),new THREE.MeshBasicMaterial({color:'#d8ff89',transparent:true,opacity:.8,depthWrite:false}));dot.rotation.x=-Math.PI/2;dot.position.set(c-3.5,.47,r-3.5);dot.visible=false;boardRoot.add(dot);targetMeshes[idx]=dot;const capture=new THREE.Mesh(new THREE.TorusGeometry(.38,.026,8,36),new THREE.MeshBasicMaterial({color:'#ff827e',transparent:true,opacity:.9}));capture.rotation.x=Math.PI/2;capture.position.set(c-3.5,.49,r-3.5);capture.visible=false;boardRoot.add(capture);captureMeshes[idx]=capture;const ring=new THREE.Mesh(new THREE.TorusGeometry(.43,.045,8,40),new THREE.MeshBasicMaterial({color:'#ff5e69',transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;ring.position.set(c-3.5,.5,r-3.5);ring.visible=false;boardRoot.add(ring);checkMeshes[idx]=ring;}
for(let c=0;c<8;c++){addLabel('abcdefgh'[c],c-3.5,4.13,0,'w');addLabel(String(8-c),-4.14,c-3.5,Math.PI/2,'w');addLabel('abcdefgh'[c],c-3.5,-4.13,Math.PI,'b');addLabel(String(c+1),-4.14,c-3.5,-Math.PI/2,'b');}
function setCoordinateSide(color){for(const side of['w','b'])for(const label of coordinateLabels[side])label.visible=side===color;}

const shapeProfiles={P:[[0,.08],[.22,.08],[.27,.12],[.27,.17],[.21,.21],[.17,.27],[.15,.36],[.12,.43],[.1,.5],[.14,.54],[.17,.6],[.16,.66],[.12,.71],[.07,.74],[0,.75]],R:[[0,.08],[.3,.08],[.35,.12],[.34,.18],[.27,.22],[.24,.29],[.24,.67],[.32,.7],[.34,.75],[.29,.79],[.29,.84],[.35,.87],[.35,.93],[.27,.96],[.25,1.02],[0,1.02]],B:[[0,.08],[.3,.08],[.34,.13],[.32,.18],[.24,.23],[.2,.34],[.15,.49],[.11,.62],[.11,.75],[.2,.8],[.24,.85],[.2,.9],[.11,.93],[.1,1.03],[.05,1.08],[0,1.08]],Q:[[0,.08],[.31,.08],[.36,.13],[.34,.19],[.26,.23],[.22,.35],[.16,.5],[.13,.67],[.18,.72],[.25,.77],[.25,.83],[.19,.87],[.12,.89],[.09,.98],[.04,1.02],[0,1.02]],K:[[0,.08],[.32,.08],[.37,.13],[.34,.2],[.26,.24],[.22,.38],[.16,.53],[.13,.71],[.21,.76],[.27,.81],[.25,.87],[.16,.91],[.13,.99],[.07,1.02],[0,1.02]]};
const pieceGeo={};for(const[t,profile]of Object.entries(shapeProfiles))pieceGeo[t]=new THREE.LatheGeometry(profile.map(([x,y])=>new THREE.Vector2(x,y)),32);
const pieceObjects=new Map(),sharedPieceMat={w:materials.white,b:materials.black};
function buildPiece(p){const g=new THREE.Group(),colorMat=sharedPieceMat[p[0]],accent=p[0]==='w'?materials.gold:materials.blueAccent,base=new THREE.Mesh(new THREE.CylinderGeometry(.29,.34,.085,32),colorMat);base.position.y=.06;base.castShadow=true;base.receiveShadow=true;g.add(base);const body=new THREE.Mesh(pieceGeo[p[1]],colorMat);body.castShadow=true;body.receiveShadow=true;g.add(body);const ringY={P:.2,N:.22,B:.24,R:.22,Q:.25,K:.25}[p[1]],ring=new THREE.Mesh(new THREE.TorusGeometry(p[1]==='R'?.3:.25,.018,8,32),accent);ring.rotation.x=Math.PI/2;ring.position.y=ringY;g.add(ring);if(p[1]==='K'){const stem=new THREE.Mesh(new THREE.BoxGeometry(.075,.28,.075),materials.gold);stem.position.y=1.12;const cross=new THREE.Mesh(new THREE.BoxGeometry(.22,.065,.065),materials.gold);cross.position.y=1.12;g.add(stem,cross);}if(p[1]==='Q'){for(let i=0;i<5;i++){const a=i*Math.PI*2/5,orb=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),materials.gold);orb.position.set(Math.cos(a)*.25,.94,Math.sin(a)*.25);g.add(orb);}}if(p[1]==='B'){const cut=new THREE.Mesh(new THREE.BoxGeometry(.028,.16,.24),accent);cut.rotation.y=.45;cut.position.set(.08,.93,0);g.add(cut);}if(p[1]==='R'){for(let i=0;i<4;i++){const a=i*Math.PI/2,crenel=new THREE.Mesh(new THREE.BoxGeometry(.1,.12,.1),colorMat);crenel.position.set(Math.cos(a)*.21,1.07,Math.sin(a)*.21);g.add(crenel);}}if(p[1]==='N'){const neck=new THREE.Mesh(new THREE.CapsuleGeometry(.135,.39,5,12),colorMat);neck.position.set(0,.57,0);neck.rotation.z=-.23;g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.17,16,12),colorMat);head.position.set(0,.91,-.09);head.scale.set(.8,1.3,1);g.add(head);const muzzle=new THREE.Mesh(new THREE.ConeGeometry(.095,.24,10),colorMat);muzzle.position.set(0,.86,-.25);muzzle.rotation.x=-Math.PI/2;g.add(muzzle);const eye=new THREE.Mesh(new THREE.SphereGeometry(.024,8,8),p[0]==='w'?materials.black:materials.ivoryAccent);eye.position.set(.105,.96,-.16);g.add(eye);}g.position.y=.48;g.userData={baseY:.48,type:p[1],color:p[0]};return g;}
function setBoardFromState(state){for(const[,o]of pieceObjects)boardRoot.remove(o);pieceObjects.clear();state.board.forEach((p,i)=>{if(p){const obj=buildPiece(p);obj.position.x=i%8-3.5;obj.position.z=Math.floor(i/8)-3.5;boardRoot.add(obj);pieceObjects.set(i,obj);}});}

let state=fromFen(),currentMode='single',humanColor='w',difficulty='medium',names={w:'You',b:'The Machine'},selected=-1,selectedMoves=[],lastMove=null,animating=false,gameStarted=false,gameEnded=false,autoCamera=true,showLast=true,topView=false,focusMode=localStorage.getItem('play.chess.focusMode')==='true',lowQuality=localStorage.getItem('play.chess.lowQuality')==='true',viewColor='w',camAzimuth=0,camTargetAzimuth=0,camRadius=23,camTargetRadius=23,camPolar=.98,camTargetPolar=.98,animationSpeed=1,frame=0,activePointer=null,raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),soundOn=true,audio=null,worker=new Worker('./ai-worker.js',{type:'module'}),workerRequest=0,clockSeconds={w:600,b:600},timerEnabled=false,clockTimer=null,toastTimer=null;
function applyQuality(){document.body.classList.toggle('low-quality',lowQuality);$('#low-quality').checked=lowQuality;roomDecor.visible=!lowQuality&&!topView;tableShadow.visible=!lowQuality&&!topView;tabletopEdge.visible=!topView;tableTop.visible=!topView;tableInlay.visible=!topView;scene.fog=lowQuality||topView?null:loungeFog;renderer.shadowMap.enabled=!lowQuality;renderer.setPixelRatio(Math.min(devicePixelRatio,lowQuality?1:1.8));}
applyQuality();
setBoardFromState(state);
const menu=$('#menu'),gameUI=$('#game-ui'),statusEl=$('#board-status'),hintEl=$('#board-hint-text');
function activeCamera(){return topView?topCamera:camera;}
function resizeRenderer(){const rect=stage.getBoundingClientRect(),width=Math.max(1,Math.round(rect.width)),height=Math.max(1,Math.round(rect.height)),aspect=width/height;renderer.setPixelRatio(Math.min(devicePixelRatio,lowQuality?1:1.8));renderer.setSize(width,height,false);camera.aspect=aspect;camera.fov=34;camera.updateProjectionMatrix();const half=4.9;if(aspect>=1){topCamera.left=-half*aspect;topCamera.right=half*aspect;topCamera.top=half;topCamera.bottom=-half;}else{topCamera.left=-half;topCamera.right=half;topCamera.top=half/aspect;topCamera.bottom=-half/aspect;}topCamera.updateProjectionMatrix();if(gameStarted&&!topView){camTargetRadius=Math.max(16.8,6.8/(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*Math.min(1,aspect))*.78);camRadius=Math.max(camRadius,camTargetRadius);}}
new ResizeObserver(resizeRenderer).observe(stage);
function applyFocusMode(){document.body.classList.toggle('game-active',gameStarted);document.body.classList.toggle('focus-mode',gameStarted&&focusMode);$('#focus-toggle').setAttribute('aria-pressed',String(focusMode));$('#focus-toggle').setAttribute('aria-label',focusMode?'Exit focus mode (H)':'Focus mode (H)');$('#focus-toggle').title=focusMode?'Exit focus mode · H':'Focus mode · H';requestAnimationFrame(resizeRenderer);}
function toggleFocusMode(){focusMode=!focusMode;localStorage.setItem('play.chess.focusMode',String(focusMode));applyFocusMode();playTone('ui');}
setCoordinateSide('w');
let ambience=null;function syncAmbience(){try{audio??=new AudioContext();if(!ambience){const master=audio.createGain();master.gain.value=.009;master.connect(audio.destination);for(const[f,type]of[[55,'sine'],[82.4,'triangle']]){const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.value=f;gain.gain.value=type==='sine'?.8:.23;osc.connect(gain).connect(master);osc.start();}ambience={master};}ambience.master.gain.setTargetAtTime(soundOn?.009:0,audio.currentTime,.35);if(soundOn&&audio.state==='suspended')audio.resume();}catch{}}
function playTone(kind='move'){if(!soundOn)return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.type=kind==='capture'?'triangle':'sine';osc.frequency.setValueAtTime(kind==='capture'?155:kind==='check'?680:kind==='ui'?520:370,now);osc.frequency.exponentialRampToValueAtTime(kind==='capture'?68:kind==='check'?480:260,now+.13);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(kind==='capture'?.065:.035,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.2);osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+.21);}catch{}}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2100);}
function squarePos(i){return new THREE.Vector3(i%8-3.5,.48,Math.floor(i/8)-3.5);}
const animations=[];function animate(duration,step,done){animations.push({start:performance.now(),duration:duration/animationSpeed,step,done});}
function moveVisual(from,to,knight=false,duration=520,delay=0){const obj=pieceObjects.get(from);if(!obj)return Promise.resolve();const a=squarePos(from),b=squarePos(to),start=performance.now()+delay;return new Promise(resolve=>{animations.push({start,duration:duration/animationSpeed,step:t=>{const eased=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;obj.position.x=THREE.MathUtils.lerp(a.x,b.x,eased);obj.position.z=THREE.MathUtils.lerp(a.z,b.z,eased);obj.position.y=.48+Math.sin(Math.PI*t)*(knight?.95:.28);obj.rotation.y=t*Math.PI*(knight?.5:.08);},done:resolve});});}
function sparkAt(pos,color='#d8ff89'){const group=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9});for(let i=0;i<14;i++){const dot=new THREE.Mesh(new THREE.SphereGeometry(.025+Math.random()*.025,6,6),mat);dot.position.set((Math.random()-.5)*.5,.3+Math.random()*.35,(Math.random()-.5)*.5);dot.userData.velocity=new THREE.Vector3((Math.random()-.5)*.025,Math.random()*.035,(Math.random()-.5)*.025);group.add(dot);}group.position.copy(pos);boardRoot.add(group);animate(480,t=>{group.children.forEach(d=>{d.position.addScaledVector(d.userData.velocity,1);});mat.opacity=1-t;group.scale.setScalar(1+t*.3);},()=>boardRoot.remove(group));}
function setChecks(){for(const r of checkMeshes)r.visible=false;const res=result(state);if(res.check){const k=kingSquareIndex(state,state.turn);if(k>=0)checkMeshes[k].visible=true;}return res;}
function kingSquareIndex(s,color){return s.board.indexOf(color+'K');}
function refreshHighlights(){targetMeshes.forEach((m,i)=>{m.visible=selectedMoves.some(x=>x.to===i&&!state.board[i]);});captureMeshes.forEach((m,i)=>{m.visible=selectedMoves.some(x=>x.to===i&&Boolean(state.board[i]));});checkMeshes.forEach(m=>m.visible=false);const res=setChecks();}
function startCameraForTurn(){if(!autoCamera)return;viewColor=currentMode==='duel'?state.turn:humanColor;camTargetAzimuth=viewColor==='w'?0:Math.PI;setCoordinateSide(viewColor);topCamera.up.set(0,0,viewColor==='w'?-1:1);topCamera.lookAt(0,0,0);}
function renderHud(){const res=result(state),turn=state.turn==='w'?'WHITE':'BLACK';$('#turn-label').textContent=`${turn} TO MOVE`;$('#white-player').classList.toggle('active-player',state.turn==='w'&&!gameEnded);$('#black-player').classList.toggle('active-player',state.turn==='b'&&!gameEnded);$('#white-player-name').textContent=names.w;$('#black-player-name').textContent=names.b;$('#move-count').textContent=String(state.history.length).padStart(2,'0');const list=$('#move-list');list.replaceChildren();for(let i=0;i<state.history.length;i+=2){const li=document.createElement('li'),num=document.createElement('span');num.textContent=`${Math.floor(i/2)+1}.`;li.append(num,document.createTextNode(state.history[i].san||''));if(state.history[i+1])li.append(document.createTextNode(` ${state.history[i+1].san||''}`));list.append(li);}list.scrollTop=list.scrollHeight;const captures={w:[],b:[]};for(const h of state.history)if(h.captured)captures[h.turn].push(h.captured);$('#white-captured').textContent=captures.w.map(p=>pieceGlyph[p]).join(' ');$('#black-captured').textContent=captures.b.map(p=>pieceGlyph[p]).join(' ');const whiteValue=captures.w.reduce((v,p)=>v+pieceValues[p[1]],0),blackValue=captures.b.reduce((v,p)=>v+pieceValues[p[1]],0),diff=whiteValue-blackValue;$('#material-score').textContent=diff===0?'EVEN POSITION':`${diff>0?'WHITE':'BLACK'} +${Math.abs(diff)}`;$('#material-detail').textContent=state.history.length?`${captures.w.length+captures.b.length} capture${captures.w.length+captures.b.length===1?'':'s'} · material advantage`:'No captures yet';if(res.over&&!gameEnded&&!animating)endGame(res.reason,res.winner);else if(gameStarted&&!gameEnded){if(res.check){statusEl.textContent='Check';hintEl.textContent=`${turn} king is under attack.`;}else{statusEl.textContent=currentMode==='single'&&state.turn===humanColor?'Your move':`${turn[0]+turn.slice(1).toLowerCase()} to move`;hintEl.textContent='Choose a piece, then choose a square.';}}}
const pieceGlyph={wK:'♔',wQ:'♕',wR:'♖',wB:'♗',wN:'♘',wP:'♙',bK:'♚',bQ:'♛',bR:'♜',bB:'♝',bN:'♞',bP:'♟'},pieceValues={P:1,N:3,B:3,R:5,Q:9,K:0};
function updateSquareStyles(){for(let i=0;i<64;i++){const tile=squareMeshes[i].children[0].material;tile.emissive?.set(0x000000);tile.emissiveIntensity=0;if(lastMove&&showLast&&(i===lastMove.from||i===lastMove.to)){tile.emissive?.set('#b49a58');tile.emissiveIntensity=.23;}if(i===selected){tile.emissive?.set('#a2e6bb');tile.emissiveIntensity=.4;}}}
function render(){refreshHighlights();updateSquareStyles();renderHud();}
function animatePieceMove(m,captured){animating=true;selected=-1;selectedMoves=[];const captureSquare=m.flags.includes('e')?m.to+(m.piece[0]==='w'?8:-8):m.to,target=squarePos(captureSquare);if(captured){const victim=pieceObjects.get(captureSquare);if(victim){pieceObjects.delete(captureSquare);animate(210,t=>{victim.rotation.z=t*.45;victim.scale.setScalar(1-t*.65);},()=>{boardRoot.remove(victim);});}sparkAt(target,'#f0bb70');}
const king=(m.flags==='kK'||m.flags==='kQ'),knight=state.board[m.from]?.[1]==='N';const promise=moveVisual(m.from,m.to,knight,captured?620:knight?700:520,captured?100:0);let rookPromise=Promise.resolve();if(king){const rookFrom=m.flags==='kK'?m.from+3:m.from-4,rookTo=m.flags==='kK'?m.from+1:m.from-1;rookPromise=moveVisual(rookFrom,rookTo,false,500,360);const rook=pieceObjects.get(rookFrom);pieceObjects.delete(rookFrom);if(rook)pieceObjects.set(rookTo,rook);}
const moving=pieceObjects.get(m.from);pieceObjects.delete(m.from);if(moving)pieceObjects.set(m.to,moving);return Promise.all([promise,rookPromise]).then(()=>{if(m.promotion&&moving){const promoted=buildPiece(m.piece[0]+m.promotion);promoted.position.x=m.to%8-3.5;promoted.position.z=Math.floor(m.to/8)-3.5;boardRoot.remove(moving);boardRoot.add(promoted);pieceObjects.set(m.to,promoted);sparkAt(target,'#a6f4d4');}animating=false;playTone(captured?'capture':m.flags.startsWith('k')?'move':'move');return true;});}
function commitMove(move){if(gameEnded||animating)return;const m={...move};if(m.flags.includes('p')&&!m.promotion){showPromotion(m);return;}const notation=san(state,m),movingPiece=state.board[m.from],captured=m.flags.includes('e')?state.board[m.to+(movingPiece[0]==='w'?8:-8)]:state.board[m.to];makeMove(state,m);state.history.at(-1).san=notation;lastMove={from:m.from,to:m.to};if(timerEnabled)clockSeconds[movingPiece[0]]=Math.max(0,clockSeconds[movingPiece[0]]);startCameraForTurn();const visuals=animatePieceMove({...m,piece:movingPiece},captured);render();if(result(state).check)playTone('check');visuals.then(()=>{if(timerEnabled)startClock();render();if(currentMode==='single'&&!gameEnded&&state.turn!==humanColor)requestAiMove();});}
function showPromotion(move){const panel=$('#promotion'),choices=$('#promotion-choices');choices.replaceChildren();for(const type of['Q','R','B','N']){const button=document.createElement('button');button.textContent=pieceGlyph[state.turn+type];button.setAttribute('aria-label',`Promote to ${type}`);button.onclick=()=>{panel.classList.add('hidden');commitMove({...move,promotion:type,flags:move.flags.replace('p','')});};choices.append(button);}panel.classList.remove('hidden');}
function onSquare(i){if(!gameStarted||gameEnded||animating||$('#settings').classList.contains('hidden')===false||$('#promotion').classList.contains('hidden')===false)return;if(currentMode==='single'&&state.turn!==humanColor)return;if(selectedMoves.some(m=>m.to===i)){const move=selectedMoves.find(m=>m.to===i);commitMove(move);return;}const p=state.board[i];if(p&&p[0]===state.turn){selected=i;selectedMoves=legalMoves(state,i);const obj=pieceObjects.get(i);if(obj)obj.position.y=.68;statusEl.textContent='Piece selected';hintEl.textContent=`${squareName(i)} · ${selectedMoves.length} legal move${selectedMoves.length===1?'':'s'}`;}else{selected=-1;selectedMoves=[];statusEl.textContent='Your move';hintEl.textContent='Choose one of your pieces.';}render();}
function requestAiMove(){if(gameEnded)return;statusEl.textContent='The machine is thinking';hintEl.textContent='Finding a line through the position…';workerRequest++;worker.postMessage({fen:toFen(state),difficulty,requestId:workerRequest});}
worker.onmessage=({data})=>{if(data.requestId!==workerRequest||gameEnded)return;const from=squareIndex(data.move.from),to=squareIndex(data.move.to),move=legalMoves(state,from).find(m=>m.to===to);if(move)commitMove({...move,promotion:data.move.promotion||undefined});};
function startClock(){if(!timerEnabled||clockTimer)return;clockTimer=setInterval(()=>{if(gameEnded)return;clockSeconds[state.turn]--;updateClocks();if(clockSeconds[state.turn]<=0){clearInterval(clockTimer);clockTimer=null;endGame('timeout',state.turn==='w'?'b':'w');}},1000);}
function updateClocks(){for(const c of['w','b']){const el=$(`#${c==='w'?'white':'black'}-clock`),sec=Math.max(0,clockSeconds[c]);el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}}
function endGame(reason,winner){if(gameEnded)return;gameEnded=true;if(clockTimer){clearInterval(clockTimer);clockTimer=null;}if(reason==='checkmate'&&winner){const loser=winner==='w'?'b':'w',king=pieceObjects.get(kingSquareIndex(state,loser));if(king)animate(850,t=>{king.rotation.z=-t*.95;king.rotation.x=t*.22;king.position.y=.48-t*.13;},()=>{});}const namesReason={checkmate:'Checkmate',stalemate:'Stalemate','threefold repetition':'Draw by repetition','fifty-move rule':'Draw by the fifty-move rule','insufficient material':'Draw · insufficient material',timeout:'Time expired',resignation:'Resignation',agreement:'Draw agreed'};$('#end-kicker').textContent=winner?`${names[winner].toUpperCase()} WINS`:'DRAW';$('#end-title').textContent=winner?`${names[winner]} wins`:'A drawn game';$('#end-copy').textContent=namesReason[reason]||reason;$('#end-modal').classList.remove('hidden');playTone('check');}
function newGame(){if(clockTimer){clearInterval(clockTimer);clockTimer=null;}state=fromFen();selected=-1;selectedMoves=[];lastMove=null;animating=false;gameEnded=false;gameStarted=true;clockSeconds={w:timerEnabled?Number($('#timer-choice').value)*60:600,b:timerEnabled?Number($('#timer-choice').value)*60:600};$('#end-modal').classList.add('hidden');$('#promotion').classList.add('hidden');menu.classList.add('hidden');gameUI.classList.remove('hidden');setBoardFromState(state);viewColor=humanColor;camTargetAzimuth=humanColor==='w'?0:Math.PI;camAzimuth=camTargetAzimuth;camTargetPolar=.98;camTargetRadius=23;topView=false;startCameraForTurn();applyFocusMode();updateClocks();$('#white-clock').classList.toggle('hidden',!timerEnabled);$('#black-clock').classList.toggle('hidden',!timerEnabled);render();syncAmbience();if(currentMode==='single'&&humanColor==='b')requestAiMove();if(timerEnabled)startClock();playTone('ui');}
function returnMenu(){gameStarted=false;gameEnded=false;document.body.classList.remove('game-active','focus-mode');if(clockTimer){clearInterval(clockTimer);clockTimer=null;}$('#end-modal').classList.add('hidden');gameUI.classList.add('hidden');menu.classList.remove('hidden');setBoardFromState(fromFen());state=fromFen();camTargetAzimuth=0;camTargetPolar=.98;camTargetRadius=14;requestAnimationFrame(resizeRenderer);}

$('#start-game').onclick=()=>{currentMode=document.querySelector('.mode-tab.active').dataset.mode;difficulty=$('#difficulty').value;timerEnabled=currentMode==='duel'&&Number($('#timer-choice').value)>0;const chosen=$('#color-choice').value;humanColor=chosen==='random'?(Math.random()<.5?'w':'b'):chosen;names=currentMode==='duel'?{w:$('#white-name').value.trim()||'White player',b:$('#black-name').value.trim()||'Black player'}:{w:humanColor==='w'?'You':'The Machine',b:humanColor==='b'?'You':'The Machine'};newGame();};
document.querySelectorAll('.mode-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b===button));const single=button.dataset.mode==='single';$('#single-options').classList.toggle('hidden',!single);$('#duel-options').classList.toggle('hidden',single);});
$('#undo-button').onclick=()=>{if(animating||!state.history.length)return;const count=currentMode==='single'&&state.turn===humanColor?Math.min(2,state.history.length):1;for(let i=0;i<count;i++)undoMove(state);lastMove=state.history.length?{from:state.history.at(-1).move.from,to:state.history.at(-1).move.to}:null;selected=-1;selectedMoves=[];setBoardFromState(state);render();toast('Last move taken back');};
$('#flip-button').onclick=()=>{viewColor=viewColor==='w'?'b':'w';camTargetAzimuth=viewColor==='w'?0:Math.PI;topView=false;pedestal.visible=true;setCoordinateSide(viewColor);topCamera.up.set(0,0,viewColor==='w'?-1:1);topCamera.lookAt(0,0,0);applyQuality();playTone('ui');};$('#top-button').onclick=()=>{topView=!topView;$('#top-button').textContent=topView?'3D VIEW':'TOP VIEW';pedestal.visible=!topView;camTargetPolar=.98;applyQuality();resizeRenderer();playTone('ui');};$('#focus-toggle').onclick=toggleFocusMode;
$('#draw-button').onclick=()=>{if(currentMode==='duel'&&window.confirm(`${names[state.turn==='w'?'b':'w']} accepts the draw?`))endGame('agreement',null);else if(currentMode==='single')toast('Draw offers are available in local duels.');};$('#resign-button').onclick=()=>{if(!window.confirm(`${names[state.turn]}, resign this game?`))return;endGame('resignation',state.turn==='w'?'b':'w');};
$('#rematch-button').onclick=newGame;$('#menu-button').onclick=returnMenu;$('#settings-open').onclick=()=>$('#settings').classList.remove('hidden');$('#settings-close').onclick=()=>$('#settings').classList.add('hidden');$('#sound-toggle').onclick=()=>{soundOn=!soundOn;$('#sound-toggle').textContent=`SOUND ${soundOn?'ON':'OFF'}`;syncAmbience();playTone('ui');};$('#auto-camera').onchange=e=>{autoCamera=e.target.checked;if(autoCamera)startCameraForTurn();};$('#show-last').onchange=e=>{showLast=e.target.checked;render();};$('#speed-choice').onchange=e=>animationSpeed=Number(e.target.value);$('#low-quality').onchange=e=>{lowQuality=e.target.checked;localStorage.setItem('play.chess.lowQuality',String(lowQuality));applyQuality();};
$('#theme-choice').onchange=e=>{neon=e.target.value==='neon';materials.light.color.set(neon?'#8ebcb2':'#e8dec7');materials.dark.color.set(neon?'#132b31':'#403b33');materials.white.color.set(neon?'#cce8d7':'#e8dfca');materials.black.color.set(neon?'#0d1e24':'#171e22');for(let i=0;i<64;i++)squareMeshes[i].children[0].material.color.set(neon?((Math.floor(i/8)+i%8)%2===0?'#b3d7c5':'#12272b'):((Math.floor(i/8)+i%8)%2===0?'#e8dec7':'#403b33'));boardBase.material.color.set(neon?'#111d25':'#30241b');trim.material.color.set(neon?'#50bdb3':'#ba9b64');};
function pickSquare(clientX,clientY){const rect=stage.getBoundingClientRect();pointer.set(((clientX-rect.left)/rect.width)*2-1,-((clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,activeCamera());const hits=raycaster.intersectObjects(squareMeshes,true);return hits.length?squareMeshes.findIndex(s=>s===hits[0].object.parent):-1;}
function canMoveNow(){return gameStarted&&!gameEnded&&!animating&&(currentMode!=='single'||state.turn===humanColor)&&$('#settings').classList.contains('hidden')&&$('#promotion').classList.contains('hidden');}
stage.addEventListener('pointerdown',e=>{const from=canMoveNow()?pickSquare(e.clientX,e.clientY):-1,p=from>=0?state.board[from]:null,dragFrom=p?.[0]===state.turn?from:-1;activePointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,dragFrom};stage.setPointerCapture(e.pointerId);if(dragFrom>=0){selected=dragFrom;selectedMoves=legalMoves(state,dragFrom);const obj=pieceObjects.get(dragFrom);if(obj)obj.position.y=.68;render();}});
stage.addEventListener('pointermove',e=>{if(!activePointer||e.pointerId!==activePointer.id)return;const dx=e.clientX-activePointer.lastX,dy=e.clientY-activePointer.lastY;if(Math.hypot(e.clientX-activePointer.x,e.clientY-activePointer.y)>5)activePointer.moved=true;if(activePointer.moved&&activePointer.dragFrom>=0){pointer.set(((e.clientX-stage.getBoundingClientRect().left)/stage.clientWidth)*2-1,-((e.clientY-stage.getBoundingClientRect().top)/stage.clientHeight)*2+1);raycaster.setFromCamera(pointer,activeCamera());const hit=raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-.48),new THREE.Vector3());if(hit){const local=boardRoot.worldToLocal(hit);const obj=pieceObjects.get(activePointer.dragFrom);if(obj){obj.position.set(local.x,.79,local.z);}}}else if(activePointer.moved&&!topView){camTargetAzimuth-=dx*.008;camTargetPolar=THREE.MathUtils.clamp(camTargetPolar+dy*.004,.22,1.38);}activePointer.lastX=e.clientX;activePointer.lastY=e.clientY;});
stage.addEventListener('pointerup',e=>{if(!activePointer||e.pointerId!==activePointer.id)return;const active=activePointer;activePointer=null;if(gameStarted&&active.dragFrom>=0&&active.moved){const destination=pickSquare(e.clientX,e.clientY),obj=pieceObjects.get(active.dragFrom);if(obj)obj.position.copy(squarePos(active.dragFrom));const moves=legalMoves(state,active.dragFrom),move=moves.find(candidate=>candidate.to===destination);if(move){commitMove(move);return;}selected=active.dragFrom;selectedMoves=moves;if(obj)obj.position.y=.68;render();return;}if(active.moved||!gameStarted)return;const idx=pickSquare(e.clientX,e.clientY);if(idx>=0)onSquare(idx);});
stage.addEventListener('pointercancel',()=>{if(activePointer?.dragFrom>=0){const obj=pieceObjects.get(activePointer.dragFrom);if(obj)obj.position.copy(squarePos(activePointer.dragFrom));}activePointer=null;});stage.addEventListener('wheel',e=>{if(!topView)camTargetRadius=THREE.MathUtils.clamp(camTargetRadius+e.deltaY*.005,10,60);},{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#settings').classList.add('hidden');$('#promotion').classList.add('hidden');if(!$('#end-modal').classList.contains('hidden'))$('#end-modal').classList.add('hidden');}if(e.key.toLowerCase()==='f'&&gameStarted)$('#flip-button').click();if(e.key.toLowerCase()==='h'&&gameStarted&&!e.repeat&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))toggleFocusMode();});

let resizeFrame=0;window.addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(resizeRenderer);});
function tick(now){requestAnimationFrame(tick);frame++;if(!lowQuality&&roomDecor.visible){for(let i=0;i<dustCount;i++){const n=i*3;dustPositions[n]+=dustDrift[n]*.016+Math.sin(now*.0003+i)*.0005;dustPositions[n+1]+=dustDrift[n+1]*.016;if(dustPositions[n+1]>8.8)dustPositions[n+1]=.35;if(dustPositions[n]<-12)dustPositions[n]=12;if(dustPositions[n]>12)dustPositions[n]=-12;}dustGeometry.attributes.position.needsUpdate=true;}for(let i=animations.length-1;i>=0;i--){const a=animations[i];if(now<a.start)continue;const t=Math.min(1,(now-a.start)/a.duration);a.step(t);if(t===1){animations.splice(i,1);a.done?.();}}if(!gameStarted){boardRoot.rotation.y=Math.sin(now*.00012)*.16;boardRoot.position.y=Math.sin(now*.0009)*.025;}else{boardRoot.rotation.y=THREE.MathUtils.damp(boardRoot.rotation.y,0,.6,.016);boardRoot.position.y=THREE.MathUtils.damp(boardRoot.position.y,0,.6,.016);}for(const[i,obj]of pieceObjects){if(i!==selected&&!animations.some(a=>a.movesPiece===obj))obj.position.y=THREE.MathUtils.damp(obj.position.y,obj.userData.baseY,.1,.016);}for(const ring of checkMeshes)if(ring.visible)ring.scale.setScalar(1+Math.sin(now*.01)*.08);const delta=THREE.MathUtils.euclideanModulo(camTargetAzimuth-camAzimuth+Math.PI,Math.PI*2)-Math.PI;camAzimuth+=delta*.045;camPolar=THREE.MathUtils.damp(camPolar,camTargetPolar,4,.016);camRadius=THREE.MathUtils.damp(camRadius,camTargetRadius,4,.016);const flat=Math.sin(camPolar)*camRadius;camera.position.set(Math.sin(camAzimuth)*flat,Math.cos(camPolar)*camRadius,Math.cos(camAzimuth)*flat);camera.lookAt(gameStarted?0:-3.2,.05,0);if(topView){topCamera.position.set(0,26,0);topCamera.lookAt(0,0,0);}renderer.render(scene,activeCamera());}
requestAnimationFrame(tick);
