// Compact chess rules engine: legal move generation, FEN state, SAN, draws and terminal results.
export const START_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
export const FILES='abcdefgh';
export const piece=(color,type)=>color+type;
export function fromFen(fen=START_FEN){const [layout,turn,castle,ep,half,full]=fen.split(' '),board=Array(64).fill(null);layout.split('/').forEach((rank,r)=>{let f=0;for(const ch of rank){if(/[1-8]/.test(ch))f+=Number(ch);else board[r*8+f++]=(ch===ch.toUpperCase()?'w':'b')+ch.toUpperCase();}});const rights={K:'wK',Q:'wQ',k:'bK',q:'bQ'},s={board,turn,castle:new Set(castle==='-'?'':[...castle].map(ch=>rights[ch])),ep:ep==='-'?-1:squareIndex(ep),half:Number(half)||0,full:Number(full)||1,history:[],keys:[]};s.keys.push(positionKey(s));return s;}
export function squareIndex(s){return FILES.indexOf(s[0])+ (8-Number(s[1]))*8;}
export function squareName(i){return FILES[i%8]+(8-Math.floor(i/8));}
export function cloneState(s){return{...s,board:s.board.slice(),castle:new Set(s.castle),history:s.history.slice(),keys:s.keys.slice()};}
const row=i=>Math.floor(i/8), col=i=>i%8, inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
export function attacked(s,target,by){const b=s.board,tr=row(target),tc=col(target),pawnDir=by==='w'?1:-1;for(const dc of[-1,1]){const r=tr+pawnDir,c=tc+dc;if(inside(r,c)&&b[r*8+c]===by+'P')return true;}for(const[dr,dc]of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]]){const r=tr+dr,c=tc+dc;if(inside(r,c)&&b[r*8+c]===by+'N')return true;}for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){let r=tr+dr,c=tc+dc;while(inside(r,c)){const p=b[r*8+c];if(p){if(p[0]===by&&(p[1]==='Q'||(Math.abs(dr)===Math.abs(dc)?p[1]==='B':p[1]==='R')))return true;break;}r+=dr;c+=dc;}}for(let r=tr-1;r<=tr+1;r++)for(let c=tc-1;c<=tc+1;c++)if(inside(r,c)&&b[r*8+c]===by+'K')return true;return false;}
export function kingSquare(s,color){return s.board.indexOf(color+'K');}
export function inCheck(s,color=s.turn){const k=kingSquare(s,color);return k<0||attacked(s,k,color==='w'?'b':'w');}
function pseudo(s,from){const b=s.board,p=b[from];if(!p)return[];const color=p[0],type=p[1],r=row(from),c=col(from),out=[];const add=(rr,cc,flags='')=>{if(!inside(rr,cc))return false;const to=rr*8+cc,q=b[to];if(q&&q[0]===color)return false;out.push({from,to,flags});return !q;};if(type==='P'){const d=color==='w'?-1:1,start=color==='w'?6:1,prom=color==='w'?0:7;if(inside(r+d,c)&&!b[(r+d)*8+c]){const to=(r+d)*8+c;out.push({from,to,flags:row(to)===prom?'p':'n'});if(r===start&&!b[(r+2*d)*8+c])out.push({from,to:(r+2*d)*8+c,flags:'b'});}for(const dc of[-1,1])if(inside(r+d,c+dc)){const to=(r+d)*8+c+dc;if(b[to]&&b[to][0]!==color)out.push({from,to,flags:row(to)===prom?'cp':'c'});else if(to===s.ep)out.push({from,to,flags:'e'});}}else if(type==='N'){for(const[dr,dc]of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+dr,c+dc);}else if(type==='K'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);const home=color==='w'?60:4,enemy=color==='w'?'b':'w';if(from===home&&!inCheck(s,color)){for(const[side,rook,through,empty,pass]of[['K',home+3,home+1,[home+1,home+2],home+1],['Q',home-4,home-1,[home-1,home-2,home-3],home-1]])if(s.castle.has(color+side)&&b[rook]===color+'R'&&empty.every(i=>!b[i])&&!attacked(s,pass,enemy)&&!attacked(s,home+(side==='K'?2:-2),enemy))out.push({from,to:home+(side==='K'?2:-2),flags:'k'+side});}}else{const dirs=type==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:type==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,dc]of dirs)for(let n=1;add(r+dr*n,c+dc*n);n++);}return out;}
export function makeMove(s,m){const b=s.board,p=b[m.from],captured=m.flags.includes('e')?b[m.to+(p[0]==='w'?8:-8)]:b[m.to],prev={board:b.slice(),turn:s.turn,castle:new Set(s.castle),ep:s.ep,half:s.half,full:s.full,move:m,captured};s.history.push(prev);b[m.to]=m.promotion?p[0]+m.promotion:p;b[m.from]=null;if(m.flags.includes('e'))b[m.to+(p[0]==='w'?8:-8)]=null;if(m.flags.startsWith('k')){const kingSide=m.flags==='kK',rookFrom=kingSide?m.from+3:m.from-4,rookTo=kingSide?m.from+1:m.from-1;b[rookTo]=b[rookFrom];b[rookFrom]=null;}if(p[1]==='K'){s.castle.delete(p[0]+'K');s.castle.delete(p[0]+'Q');}if(p[1]==='R'){if(m.from===63)s.castle.delete('wK');if(m.from===56)s.castle.delete('wQ');if(m.from===7)s.castle.delete('bK');if(m.from===0)s.castle.delete('bQ');}if(captured?.[1]==='R'){if(m.to===63)s.castle.delete('wK');if(m.to===56)s.castle.delete('wQ');if(m.to===7)s.castle.delete('bK');if(m.to===0)s.castle.delete('bQ');}s.ep=m.flags.includes('b')?(m.from+m.to)>>1:-1;s.half=p[1]==='P'||captured?0:s.half+1;if(s.turn==='b')s.full++;s.turn=s.turn==='w'?'b':'w';s.keys.push(positionKey(s));return{...m,piece:p,captured,prev};}
export function undoMove(s){const h=s.history.pop();if(!h)return false;s.board=h.board;s.turn=h.turn;s.castle=h.castle;s.ep=h.ep;s.half=h.half;s.full=h.full;s.keys.pop();return h;}
export function legalMoves(s,from=null){const color=from===null?s.turn:s.board[from]?.[0];if(!color)return[];const candidates=from===null?s.board.flatMap((p,i)=>p?.[0]===color?pseudo(s,i):[]):pseudo(s,from);return candidates.filter(m=>{const t=cloneState(s);makeMove(t,m);return !inCheck(t,color);});}
export function positionKey(s){return s.board.map(p=>p||'--').join('')+' '+s.turn+' '+[...s.castle].sort().join('')+' '+(s.ep<0?'-':squareName(s.ep));}
export function insufficient(s){const pieces=s.board.filter(p=>p&&p[1]!=='K');if(!pieces.length)return true;if(pieces.some(p=>p[1]==='P'||p[1]==='R'||p[1]==='Q'))return false;if(pieces.length===1)return true;if(pieces.every(p=>p[1]==='B')){const colors=s.board.flatMap((p,i)=>p?.[1]==='B'?[(row(i)+col(i))%2]:[]);return colors.every(v=>v===colors[0]);}return false;}
export function result(s){const moves=legalMoves(s),check=inCheck(s);if(!moves.length)return check?{over:true,reason:'checkmate',winner:s.turn==='w'?'b':'w'}:{over:true,reason:'stalemate',winner:null};const repetitions=s.keys.filter(k=>k===positionKey(s)).length;if(repetitions>=3)return{over:true,reason:'threefold repetition',winner:null};if(s.half>=100)return{over:true,reason:'fifty-move rule',winner:null};if(insufficient(s))return{over:true,reason:'insufficient material',winner:null};return{over:false,check};}
export function san(s,m){const p=s.board[m.from],capture=m.flags.includes('c')||m.flags.includes('e'),name=p[1]==='P'?'':p[1],others=legalMoves(s).filter(o=>o.to===m.to&&o.from!==m.from&&s.board[o.from]===p);let dis='';if(others.length){const sameFile=others.some(o=>col(o.from)===col(m.from)),sameRank=others.some(o=>row(o.from)===row(m.from));dis=!sameFile?FILES[col(m.from)]:!sameRank?String(8-row(m.from)):squareName(m.from);}let text=m.flags==='kK'?'O-O':m.flags==='kQ'?'O-O-O':`${name}${capture&&p[1]==='P'?FILES[col(m.from)]:''}${dis}${capture?'x':''}${squareName(m.to)}${m.promotion?'='+m.promotion:''}`;const t=cloneState(s);makeMove(t,m);const r=result(t);return text+(r.reason==='checkmate'?'#':r.check?'+':'');}
export function toFen(s){let ranks=[];for(let r=0;r<8;r++){let e=0,line='';for(let c=0;c<8;c++){const p=s.board[r*8+c];if(!p)e++;else{if(e)line+=e,e=0;line+=p[0]==='w'?p[1]:p[1].toLowerCase();}}if(e)line+=e;ranks.push(line);}const notation=['wK','wQ','bK','bQ'].filter(k=>s.castle.has(k)).map(k=>({wK:'K',wQ:'Q',bK:'k',bQ:'q'}[k])).join('');return`${ranks.join('/')} ${s.turn} ${notation||'-'} ${s.ep<0?'-':squareName(s.ep)} ${s.half} ${s.full}`;}
