import * as THREE from 'three';
import type { Viewpoint } from './CameraRig';
export class CameraSafety {
  boxes:{box:THREE.Box3;object:THREE.Mesh}[]=[];
  constructor(private scene:THREE.Scene){}
  refresh(){this.scene.updateMatrixWorld(true);this.boxes=[];this.scene.traverse(o=>{if(!(o instanceof THREE.Mesh)||o instanceof THREE.InstancedMesh||o.geometry.type.includes('Plane')||o.geometry.type.includes('Cone'))return;let node:THREE.Object3D|null=o;while(node){if(!node.visible||node.userData.cameraIgnore)return;node=node.parent;}const materials=Array.isArray(o.material)?o.material:[o.material];if(materials.every(m=>m.transparent&&m.opacity<.5))return;const box=new THREE.Box3().setFromObject(o);if(!box.isEmpty())this.boxes.push({box:box.expandByScalar(.055),object:o});});}
  inside(p:THREE.Vector3){return this.boxes.find(b=>b.box.containsPoint(p));}
  clear(a:THREE.Vector3,b:THREE.Vector3){const length=a.distanceTo(b);if(length<.001)return !this.inside(a);const ray=new THREE.Ray(a,b.clone().sub(a).normalize());return !this.boxes.some(({box})=>{if(box.containsPoint(a))return true;const hit=ray.intersectBox(box,new THREE.Vector3());return hit&&hit.distanceTo(a)<length-.02;});}
  occluded(eye:THREE.Vector3,target:THREE.Vector3,subject?:THREE.Object3D){const ray=new THREE.Raycaster(eye,target.clone().sub(eye).normalize(),.03,eye.distanceTo(target)-.04);const hits=ray.intersectObjects(this.boxes.map(b=>b.object),false);return hits.find(hit=>{let n:THREE.Object3D|null=hit.object;while(n){if(n===subject)return false;n=n.parent;}return true;});}
  route(from:THREE.Vector3,to:THREE.Vector3){if(this.clear(from,to))return [from.clone(),to.clone()];const nodes=[from.clone(),to.clone()];for(const y of [4.35,3.5,2.7,1.1])for(const z of [5,3.3,1.7,-1.6])for(const x of [-5,-3,0,3,5]){const p=new THREE.Vector3(x,y,z);if(!this.inside(p))nodes.push(p);}const distances=nodes.map(()=>Infinity),prev=nodes.map(()=>-1),visited=new Set<number>();distances[0]=0;for(let step=0;step<nodes.length;step++){let u=-1;for(let i=0;i<nodes.length;i++)if(!visited.has(i)&&(u<0||distances[i]<distances[u]))u=i;if(u<0||!isFinite(distances[u]))break;if(u===1){const path=[];for(let n=1;n>=0;n=prev[n])path.unshift(nodes[n]);return path;}visited.add(u);for(let v=1;v<nodes.length;v++){if(visited.has(v))continue;const d=distances[u]+nodes[u].distanceTo(nodes[v]);if(d<distances[v]&&this.clear(nodes[u],nodes[v])){distances[v]=d;prev[v]=u;}}}throw new Error('No collision-free camera path to viewpoint');}
  audit(views:Record<string,Viewpoint>,fit:(v:Viewpoint)=>Viewpoint){this.refresh();const failures:string[]=[];for(const[id,raw]of Object.entries(views)){const v=fit(raw),eye=new THREE.Vector3(...v.eye),target=new THREE.Vector3(...v.target);if(this.inside(eye))failures.push(id+': camera inside geometry');if(v.subject&&this.occluded(eye,target,v.subject))failures.push(id+': subject occluded by '+this.occluded(eye,target,v.subject)!.object.parent?.name+' at '+this.occluded(eye,target,v.subject)!.object.getWorldPosition(new THREE.Vector3()).toArray().join(','));}console.info('[Viewpoint check]',failures.length?'FAIL '+failures.join('; '):'PASS — zero failures');return failures;}
}
