import type { Settings, RoomSave } from '../engine/SaveSystem';
import { items, type Inventory } from '../engine/Inventory';
import type { LevelDefinition } from '../engine/Level';
export type Action={id:string;label:string;disabled?:boolean;primary?:boolean};
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class HUD {
  root:HTMLElement;
  action:(id:string)=>void=()=>{};
  constructor(){this.root=document.querySelector('#ui')!;this.root.innerHTML=`
    <header class="topbar"><a class="brand" href="https://play.aravindmarri.com/"><strong>ARAVIND</strong><span>/</span><span>The Locked Room</span></a><nav aria-label="Game controls"><button data-action="back" id="back" hidden>← Back</button><button data-action="hint" id="hint-button" hidden>Hint</button><button data-action="pause" id="pause-button" hidden aria-label="Pause game">Ⅱ</button><button data-action="mute" id="mute-button" aria-label="Toggle sound">Sound on</button></nav></header>
    <div class="loading" id="loading"><p class="eyebrow">ARAVIND PRESENTS</p><h1>The Locked Room</h1><p id="load-label">Opening the study…</p><progress id="load-progress" max="100" value="0"></progress><span id="load-detail"></span></div>
    <main id="title-screen" class="title-screen" hidden><section><p class="eyebrow"><span class="rule"></span> A ROOM. A SECRET. A WAY OUT.</p><h1>THE<br>LOCKED<br><em>ROOM</em><span class="title-period">.</span></h1><div class="chapter"><span>01</span><div><p>THE STUDY</p><small>The last night of Elias Vance</small></div></div><p class="intro">The fire is cold. The clock has stopped.<br>Someone meant for you to find this place.</p><button class="primary enter" data-action="enter"><span id="enter-label">Enter the study</span><span>↗</span></button><div class="title-links"><button data-action="levels">Levels</button><span>·</span><button data-action="settings">Settings</button></div><p class="quiet">HEADPHONES RECOMMENDED <span>·</span> TAKE YOUR TIME</p></section></main>
    <div id="room-label" class="room-label" hidden><span class="eyebrow">CHAPTER I</span><h2>The Study</h2><p>Every silence keeps a secret.</p></div>
    <section id="context" class="context" hidden aria-label="Examine object"><p class="eyebrow" id="context-type">A CLOSER LOOK</p><h2 id="context-title"></h2><p id="context-copy"></p><div id="actions" class="actions"></div><div id="dials" class="dials" hidden><p class="dial-instruction">Drag a dial, or focus it and use ↑ / ↓.</p><div class="dial-row">${['Moon','Candle','Key','Bird'].map((name,i)=>`<div class="dial-cell"><span class="dial-symbol" aria-hidden="true">${['☾','Candle','⚿','Bird'][i]}</span><span class="dial-name">${name}</span><button aria-label="Increase ${name.toLowerCase()} dial" data-action="dial-up-${i}">⌃</button><button class="dial" role="spinbutton" aria-label="${name} dial" aria-valuemin="0" aria-valuemax="9" aria-valuenow="0" id="dial-${i}" data-dial="${i}">0</button><button aria-label="Decrease ${name.toLowerCase()} dial" data-action="dial-down-${i}">⌄</button></div>`).join('')}</div></div><p id="inspect-help" class="inspect-help" hidden>Drag to turn · Scroll or pinch to zoom</p></section>
    <div class="hover-label" id="hover-label"></div><div id="toast" class="toast" role="status" aria-live="polite"></div><div id="caption" class="caption" role="status" aria-live="polite"></div>
    <div id="game-bottom" hidden><nav class="locations" aria-label="Room viewpoints">${[['room','Overview'],['desk','Desk'],['lamp','Lamp'],['candle','Candles'],['hooks','Key board'],['cage','Birdcage'],['painting','Painting'],['clock','Clock'],['shelf','Books'],['window','Window'],['mural','Look up'],['door','Door']].map(([id,label])=>`<button data-action="view-${id}" data-view="${id}">${label}</button>`).join('')}</nav><footer class="inventory"><span class="inventory-label">POCKETS</span><div id="inventory-items"></div><span id="inventory-empty">Nothing carried. Everything noticed.</span><button data-action="clear-item" id="clear-item" hidden>Put away ×</button></footer></div>
    <dialog id="modal"><button class="close-modal" data-action="close-modal" aria-label="Close dialog">×</button><div id="modal-content"></div></dialog><div class="exit-fade" id="exit-fade"></div>`;
    this.root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(b&&!(b as HTMLButtonElement).disabled)this.action(b.dataset.action!);});
    this.root.querySelectorAll<HTMLElement>('[data-dial]').forEach(el=>{let y:number|null=null;el.addEventListener('pointerdown',e=>{y=e.clientY;el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(y!==null&&Math.abs(e.clientY-y)>18){this.action(`dial-${e.clientY<y?'up':'down'}-${el.dataset.dial}`);y=e.clientY;}});el.addEventListener('pointerup',()=>y=null);el.addEventListener('pointercancel',()=>y=null);el.addEventListener('keydown',e=>{if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].includes(e.key)){e.preventDefault();this.action(`dial-${['ArrowUp','ArrowRight'].includes(e.key)?'up':'down'}-${el.dataset.dial}`);}});});
    this.$<HTMLDialogElement>('modal').addEventListener('cancel',e=>{e.preventDefault();this.action('close-modal');});
  }
  $<T extends HTMLElement=HTMLElement>(id:string){return document.getElementById(id) as T;}
  hide(id:string,value=true){this.$(id).hidden=value;}
  text(id:string,value:string){this.$(id).textContent=value;}
  configure(level:LevelDefinition){this.root.querySelector('.chapter>span')!.textContent=String(level.id).padStart(2,'0');this.root.querySelector('.chapter p')!.textContent=level.title.toUpperCase();this.root.querySelector('.chapter small')!.textContent=level.subtitle;this.root.querySelector('#room-label h2')!.textContent=level.title;this.root.querySelector('#room-label .eyebrow')!.textContent=`ROOM ${String(level.id).padStart(2,'0')}`;if(level.id!==1)this.root.querySelector('.intro')!.textContent=level.subtitle;}
  progress(percent:number,label:string,detail=''){this.$<HTMLProgressElement>('load-progress').value=percent;this.text('load-label',label);this.text('load-detail',detail);}
  ready(resume:boolean){this.hide('loading');this.hide('title-screen',false);this.text('enter-label',resume?'Continue the study':'Enter the study');}
  play(){this.hide('title-screen');this.hide('game-bottom',false);this.hide('room-label',false);this.hide('hint-button',false);this.hide('pause-button',false);}
  context(title:string,copy:string,actions:Action[],inspection=false){this.hide('context',false);this.text('context-title',title);this.text('context-copy',copy);this.$('actions').innerHTML=actions.map(a=>`<button data-action="${a.id}" ${a.disabled?'disabled':''} class="${a.primary?'primary':''}">${escape(a.label)}</button>`).join('');this.hide('inspect-help',!inspection);this.hide('dials');this.hide('room-label');}
  room(){this.hide('context');this.hide('back');this.hide('room-label',false);}
  toast(message:string){this.text('toast',message);this.$('toast').classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>this.$('toast').classList.remove('visible'),7000);}
  private toastTimer=0;
  private captionTimer=0;
  caption(message:string,enabled:boolean){if(!enabled)return;this.text('caption',message);this.$('caption').classList.add('visible');clearTimeout(this.captionTimer);this.captionTimer=window.setTimeout(()=>this.$('caption').classList.remove('visible'),3500);}
  inventory(inventory:Inventory){this.hide('inventory-empty',inventory.contents.size>0);this.hide('clear-item',!inventory.selected);this.$('inventory-items').innerHTML=[...inventory.contents].map(id=>`<button draggable="true" data-action="item-${id}" data-item="${id}" class="item ${inventory.selected===id?'selected':''}" aria-pressed="${inventory.selected===id}" aria-label="Select ${items[id].name}" title="${items[id].description}"><span>${items[id].glyph}</span><small>${items[id].name}</small></button>`).join('');this.$('inventory-items').querySelectorAll<HTMLElement>('[draggable]').forEach(el=>el.addEventListener('dragstart',e=>{if(inventory.selected!==el.dataset.item)this.action(`item-${el.dataset.item}`);e.dataTransfer?.setData('text/plain',el.dataset.item!);}));}
  dials(values:number[]){this.hide('dials',false);values.forEach((v,i)=>{const el=this.$(`dial-${i}`);el.textContent=String(v);el.setAttribute('aria-valuenow',String(v));});}
  dialog(html:string){this.$('modal-content').innerHTML=html;this.$<HTMLDialogElement>('modal').showModal();}
  close(){this.$<HTMLDialogElement>('modal').close();}
  settings(settings:Settings){this.dialog(`<p class="eyebrow">MAKE YOURSELF AT HOME</p><h2>Settings</h2><div class="settings"><label>Quality<select id="quality"><option value="auto">Automatic</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Volume<input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label>${[['muted','Mute sound'],['invert','Invert look'],['reduced','Reduced motion'],['captions','Sound captions']].map(([id,label])=>`<label>${label}<input type="checkbox" id="${id}" ${settings[id as keyof Settings]?'checked':''}></label>`).join('')}</div><button class="primary" data-action="save-settings">Save settings</button>`);this.$<HTMLSelectElement>('quality').value=settings.quality;}
  completed(save:RoomSave,ending:string,title='The Study',id=1,nextId?:number){this.dialog(`<p class="eyebrow">ROOM ${String(id).padStart(2,'0')} · COMPLETE</p><h2>${escape(title)}</h2><p class="escaped">Escaped.</p><p>${escape(ending)}</p><div class="stats"><div><strong>${Math.floor(save.seconds/60)}:${String(Math.floor(save.seconds%60)).padStart(2,'0')}</strong><span>TIME TAKEN</span></div><div><strong>${save.hints}</strong><span>HINTS USED</span></div></div><button ${nextId?`data-action="level-${nextId}"`:'disabled'} class="primary">${nextId?'Next room ↗':'Next room — coming soon'}</button><a class="arcade-button" href="https://play.aravindmarri.com/">Back to Arcade ↗</a><button data-action="restart">Revisit this room</button>`);}
}
