import * as THREE from 'three';
import type { Game, LevelController } from '../../engine/Game';
import type { Action } from '../../ui/HUD';
import { items } from '../../engine/Inventory';
import { textTexture, engraving } from './materials';
export function createStudy(game:Game):LevelController {
  const {room,puzzle,inventory,hud,motion,audio}=game;const o=room.objects;
  let heating=false,moonTimer=0,musicTime=-1,chimes=0,melody=0;const birdRest=.22;const dialTokens=[0,0,0,0];
  const labelDial=(i:number)=>{};
  const has=(flag:string)=>puzzle.has(flag);
  const show=(title:string,copy:string,actions:Action[]=[],inspect=false)=>hud.context(title,copy,actions,inspect);
  const button=(id:string,label:string,primary=false):Action=>({id,label,primary});
  const sound=(kind:string,id:string,caption:string,freq?:number)=>audio.sound(kind,o[id]?.getWorldPosition(new THREE.Vector3()),caption,freq);
  async function move(object:THREE.Object3D,property:'x'|'y'|'z',to:number,rotate=false,duration=.65){game.busy=true;const vector=rotate?object.rotation:object.position;const from=vector[property];await motion.to(duration,t=>vector[property]=from+(to-from)*t);game.busy=false;}
  function view(id:string){
    heating=false;
    if(id==='room'){hud.room();return;}
    if(id==='desk')show('The writing desk',has('drawer')?'A letter and a matchbox lay among the clockmaker’s papers.':has('latch')?'A small click below. The drawer no longer resists.':'The drawer moves a fraction, then catches on something underneath.',has('drawer')?[button('inspect-letter','Read the letter'),button('inspect-matches','Inspect the matchbox')]:has('latch')?[button('open-drawer','Pull the drawer',true)]:[button('underside','Look underneath'),button('try-drawer','Try the drawer')]);
    else if(id==='underside')show('A small brass latch',has('latch')?'The catch is released. The drawer is free.':'Hidden beneath the front lip: a small brass catch, worn smooth by a thumb.',has('latch')?[button('view-desk','Return to the drawer',true)]:[button('release-latch','Release the latch',true)]);
    else if(id==='candle')show(has('candle')?'A borrowed light':'The candelabra',has('candle')?'The wax softens. A gentle heat gathers above the flames.':'Three pale candles. The wicks have never been burned.',has('candle')?[...(inventory.has('letter')?[button('inspect-letter','Inspect Elias’s letter',true)]:[])]:[button('light-candle',inventory.selected==='match'?'Light with your match':'Use a lit match',true)]);
    else if(id==='lamp')show('The desk lamp',has('lampOff')?'With the lamp dark, the room seems to hold its breath.':'Warm light pools over the desk. A little switch waits below the shade.',[button('lamp-toggle',has('lampOff')?'Switch the lamp on':'Switch the lamp off',true)]);
    else if(id==='hooks')show('Six brass hooks','Six numbered plates. Five keys. Beneath the empty hook, dust keeps the shape of what is missing.',[button('study-hooks','Examine the empty hook',true)]);
    else if(id==='cage')show('A captive song',has('bird')?'The melody is familiar now. You can wind the box again.':has('cage')?'A tiny brass bird sits atop a music box. Its winding key is within reach.':'Inside the brass cage, a music box has been waiting in silence.',has('cage')?[button('wind','Wind the music box',true),button('inspect-music','Inspect the music box')]:[button('open-cage','Open the cage',true)]);
    else if(id==='painting')show('Moon over a quiet sea',has('painting')?'Behind the painting: a safe, cold as the sea in the picture.':has('straight')?'The frame rests level. There is a narrow track behind it.':'The painting hangs slightly crooked. A crescent is reflected on an empty sea.',has('painting')?[button('view-safe','Examine the safe',true),button('inspect-painting','Inspect the painting')]:[button(has('straight')?'slide-painting':'straighten',has('straight')?'Slide the painting aside':'Straighten the painting',true),button('inspect-painting','Inspect the frame')]);
    else if(id==='safe'){
      if(!has('painting')){view('painting');return;}
      if(has('safe'))show('The open safe','Warm light touches two objects: an iron key, and an envelope sealed with II.',[...(!inventory.has('key')&&!has('escape')?[button('take-key','Take the iron key',true)]:[]),...(!inventory.has('envelope')?[button('take-envelope','Take the sealed envelope')]:[])]);
      else{show('Four quiet symbols','Moon. Candle. Key. Bird. The mechanism waits for four memories in their proper order.',[button('unlock-safe','Turn the handle',true)]);hud.dials(game.roomSave.dials);}
    }
    else if(id==='clock')show('The night he left','Stopped at 3:15. A small plaque reads: “Stopped the night he left.” The clock is a memory, not a combination.');
    else if(id==='window')show('Rain, and nothing beyond','Water threads down the glass. Outside, the moon is the only witness.');
    else if(id==='shelf')show('A lifetime in margins','Two slim diaries interrupt the rows of books. Their spines bear dates, not titles.',[button('diary-1','Read the first diary'),button('diary-2','Read the second diary')]);
    else if(id==='mural')show('Above the everyday',has('lampOff')?'Slowly, old phosphorescent paint wakes in the darkness. Let your eyes trace the stars.':'Faint paint among the ceiling mouldings. The desk lamp washes out its details.',[]);
    else if(id==='door'||id==='lock')show('The oak door',has('key')?'The iron key feels right for this lock.':'The handle is cold. A heavy lock keeps the oak door shut.',[button('use-key',inventory.selected==='key'?'Use the iron key':'Try the lock',has('key')),button(id==='lock'?'view-door':'view-lock',id==='lock'?'See the whole door':'Examine the lock')]);
  }
  async function inspect(id:string){
    const source=id==='music'?'musicInspect':id;await game.inspect(source);
    if(id==='letter')show('Elias’s letter','“The light remembers what the ink forgets. The sea keeps the safe. — E.V.”',has('heat')?[button('letter-warm','See the hidden writing again')]:[button('letter-warm','Hold near the candle',true)],true);
    else if(id==='painting')show('The old frame','A canvas can keep secrets on both sides.',[button('turn-painting','Turn it over',true)],true);
    else if(id==='matches')show('Safety matches','A rough striking edge, and a handful of dry matches.',[button('strike','Strike a match',true)],true);
    else if(id==='music')show('The music box','A pinned cylinder, a winding key, a small brass bird. Someone built this to be listened to.',[],true);
    else show(items[id]?.name||'A closer look',items[id]?.description||'',[],true);
  }
  async function action(id:string){
    if(id.startsWith('touch-')){const target=id.slice(6);if(target==='candle'&&inventory.selected==='match')id='light-candle';else if(target==='door'&&inventory.selected==='key')id='use-key';else{view(target);return;}}
    if(id.startsWith('selected-')){const item=id.slice(9);if(item==='key'){view(game.viewId);hud.toast('Iron key selected. Use it at the oak door.');return;}if(inventory.selected){show(items[item].name,items[item].description,[button(`inspect-${item}`,'Inspect'),...(item==='matches'?[button('strike','Strike a match',true)]:[])]);hud.toast(`${items[item].name} selected. Choose where to use it.`);}else view(game.viewId);return;}
    if(id.startsWith('inspect-')){const target=id.slice(8);if(['letter','matches','key','envelope'].includes(target)&&!inventory.has(target)){hud.toast('You have not found that object yet.');return;}await inspect(target);return;}
    if(id==='underside'){await game.go('underside');return;}
    if(id==='try-drawer'){sound('slide','desk','[Wood catches against a metal stop]');hud.toast('Something catches beneath the drawer.');return;}
    if(id==='release-latch'&&!has('latch')){await move(o.latch,'z',-.6,true,.35);puzzle.set('latch');sound('click','desk','[A small brass catch clicks free]');view('underside');return;}
    if(id==='open-drawer'&&has('latch')&&!has('drawer')){sound('slide','desk','[The drawer slides open]');await move(o.drawer,'z',1);await game.go('drawer');show('Inside the drawer','A folded letter and a matchbox rest among loose papers.');await motion.to(1.1,()=>{});await motion.to(.45,t=>{o.drawerMatches.scale.setScalar(.7*(1-t));o.drawerLetter.scale.setScalar(.65*(1-t));});puzzle.set('drawer');inventory.add('matches');inventory.add('letter');hud.toast('Matchbox and Elias’s letter added to your pockets.');view('desk');return;}
    if(id==='strike'&&inventory.has('matches')){await game.inspect('strike');const stick=game.inspector.group.getObjectByName('matchStick')!;const flame=stick.getObjectByName('matchFlame')!;flame.visible=false;await move(stick,'y',-.13,false,.35);sound('match','desk','[A match strikes, then catches]');flame.visible=true;puzzle.set('match');inventory.add('match');inventory.selected='match';hud.inventory(inventory);show('A small flame','The match catches. Bring it to the candelabra.',[button('view-candle','Go to the candelabra',true)],true);return;}
    if(id==='light-candle'){if(has('candle'))return;if(inventory.selected!=='match'||!inventory.has('match')){hud.toast('Select a lit match from your pockets first.');return;}game.inspector.close();puzzle.set('candle');inventory.remove('match');sound('match','candle','[Three candle wicks catch, softly crackling]');audio.ambience('fire',room.flamePosition.toArray(),.04);view('candle');return;}
    if(id==='letter-warm'){
      if(!has('candle')){hud.toast('The candle is cold. A flame must come first.');return;}
      if(!inventory.has('letter'))return;game.inspector.close();await game.go('candle');await game.inspect('letter');game.inspector.anchored=true;const letterStart=game.inspector.group.position.clone(),letterEnd=room.flamePosition.clone().add(new THREE.Vector3(0,.78,.12));await motion.to(.55,t=>game.inspector.group.position.lerpVectors(letterStart,letterEnd,t*t*(3-2*t)));game.inspector.group.scale.setScalar(.95);game.busy=true;await game.rig.go({eye:[-.3,3.1,3.5],target:[-.62,2.6,.12],bounds:new THREE.Box3(new THREE.Vector3(-1.02,2.12,-.1),new THREE.Vector3(-.21,3.62,.36))});game.inspector.group.quaternion.copy(game.rig.camera.quaternion);game.busy=false;heating=true;show('What the ink forgets','Hold still. The warmth is waking something in the paper.',[],true);return;
    }
    if(id==='lamp-toggle'){if(has('lampOff')){puzzle.flags.delete('lampOff');game.persist();}else puzzle.set('lampOff');sound('click','lamp','[The lamp switch clicks]');view('lamp');return;}
    if(id==='study-hooks'){puzzle.set('hooks');show('Where a key once hung','An empty hook keeps a pale dust outline. Its teeth echo the symbol on the safe.');sound('click','hooks','[A loose brass hook taps the board]');return;}
    if(id==='open-cage'&&!has('cage')){await move(o.cageDoor,'y',-1.55,true);puzzle.set('cage');sound('door','cage','[The little cage door creaks open]');view('cage');return;}
    if(id==='wind'&&has('cage')){if(musicTime>=0){hud.toast('Listen. Let the little song finish.');return;}musicTime=0;chimes=0;melody=0;show('A song without words','A melody, then a pause. Listen to what follows. Watch the little bird.',[]);sound('click','cage','[The winding key turns]');return;}
    if(id==='straighten'&&!has('straight')){await move(o.painting,'z',0,true,.5);puzzle.set('straight');sound('slide','painting','[The frame settles level]');view('painting');return;}
    if(id==='turn-painting'&&game.inspector.active){await move(game.inspector.group,'y',game.inspector.group.rotation.y+Math.PI,true);show('A note on the frame','“Look up when the lights go out.”',[],true);return;}
    if(id==='slide-painting'&&has('straight')&&!has('painting')){game.inspector.close();sound('slide','painting','[A frame slides along a hidden rail]');await move(o.painting,'x',-.35);puzzle.set('painting');view('painting');return;}
    if(id.startsWith('dial-')&&has('painting')&&!has('safe')){const [,direction,s]=id.split('-'),index=Number(s);if(!Number.isInteger(index)||index<0||index>3)return;const delta=direction==='up'?1:-1;game.roomSave.dials[index]=(game.roomSave.dials[index]+delta+10)%10;hud.dials(game.roomSave.dials);game.rig.shake();sound('click','safe','[A dial clicks into place]',400+index*85);const dial=o[`dial${index}`];const from=dial.rotation.z,to=from+Math.atan2(Math.sin(game.roomSave.dials[index]*Math.PI/5-from),Math.cos(game.roomSave.dials[index]*Math.PI/5-from)),token=++dialTokens[index];labelDial(index);void motion.to(.3,t=>{if(token===dialTokens[index])dial.rotation.z=from+(to-from)*t;});game.persist();return;}
    if(id==='unlock-safe'&&has('painting')&&!has('safe')){if(game.roomSave.dials.join('')!=='9247'){sound('click','safe','[The mechanism stops. The handle will not turn.]');hud.toast('The mechanism resists. Not quite.');return;}
      sound('door','safe','[Four pins settle. The heavy safe lock releases.]');await move(o.safeBolts,'x',-.14,false,.35);await move(o.safeHandle,'z',Math.PI/2,true,.45);void motion.to(1,t=>(o.safeLight as THREE.PointLight).intensity=1.1*t);await move(o.safeDoor,'y',-1.65,true,1.1);puzzle.set('safe');o.safeKey.visible=true;o.safeEnvelope.visible=true;view('safe');return;}
    if(id==='take-key'&&has('safe')&&!has('key')){puzzle.set('key');inventory.add('key');o.safeKey.visible=false;view('safe');hud.toast('Iron key added to your pockets.');return;}
    if(id==='take-envelope'&&has('safe')){inventory.add('envelope');o.safeEnvelope.visible=false;await inspect('envelope');return;}
    if(id==='use-key'){if(!inventory.has('key')||inventory.selected!=='key'){hud.toast(has('key')?'Select the iron key in your pockets, then try the lock.':'The door is locked. Its key must be somewhere in the study.');return;}await game.go('lock');game.busy=true;document.body.dataset.escape='key';const key=o.key.clone(true);key.scale.setScalar(.3);key.rotation.x=Math.PI/2;const hole=o.lock.getWorldPosition(new THREE.Vector3());key.position.copy(hole).add(new THREE.Vector3(0,0,.22));game.scene.add(key);await motion.to(.65,t=>key.position.z=hole.z+.22-.18*t);await motion.to(.65,t=>key.quaternion.setFromAxisAngle(new THREE.Vector3(0,0,1),-Math.PI/2*t).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2)));sound('click','door','[A heavy lock clicks open]');await motion.to(.4,t=>o.doorHandle.rotation.z=-.4*t);key.visible=false;game.busy=false;await game.go('door');game.busy=true;document.body.dataset.escape='swing';sound('door','door','[Oak hinges creak. Warm air enters the study.]');await motion.to(2.5,t=>{const ease=t<.85?Math.sin(t/.85*Math.PI/2)*1.025:1.025-(t-.85)/.15*.025;o.oakDoor.rotation.y=1.55*ease;(o.corridorLight as THREE.SpotLight).intensity=35*t;((o.escapeBeam as THREE.Mesh).material as THREE.ShaderMaterial).uniforms.strength.value=.07*t;((o.escapeDust as THREE.Points).material as THREE.PointsMaterial).opacity=.65*t;(o.escapeWarm as THREE.HemisphereLight).intensity=.35*t;});inventory.remove('key');document.body.dataset.escape='corridor';await game.finish();return;}
    if(id==='diary-1'||id==='diary-2'){const name=id==='diary-1'?'The first diary':'The second diary',lines=id==='diary-1'?['October 12, 1891','The tower keeps time for everyone','but me. I have hidden a little','warmth here, should anyone follow.']:['October 19, 1891','I left the clock at the hour','I last heard her footsteps.','Do not wind it. Remember her.'];const page=new THREE.Mesh(new THREE.PlaneGeometry(.75,1),new THREE.MeshPhysicalMaterial({map:textTexture(name,lines,'#d3c09a','#342d26',768,1024),side:THREE.DoubleSide,roughness:.9}));o.diary=page;await game.inspect('diary');show(name,lines.join(' '),[],true);return;}
  }
  function restore(){if(has('latch'))o.latch.rotation.z=-.6;if(has('drawer')){o.drawer.position.z=1;o.drawerMatches.visible=false;o.drawerLetter.visible=false;}if(has('cage'))o.cageDoor.rotation.y=-1.55;if(has('straight'))o.painting.rotation.z=0;if(has('painting'))o.painting.position.x=-.35;if(has('safe')){o.safeDoor.rotation.y=-1.65;o.safeHandle.rotation.z=Math.PI/2;(o.safeLight as THREE.PointLight).intensity=1.1;o.safeKey.visible=!has('key');o.safeEnvelope.visible=!inventory.has('envelope');}room.heat.value=has('heat')?1:game.roomSave.heat;game.roomSave.dials.forEach((value,i)=>{o[`dial${i}`].rotation.z=value*Math.PI/5;labelDial(i);});}
  function tick(dt:number,time:number){
    if(heating&&game.inspector.active&&has('candle')){const distance=game.inspector.group.position.distanceTo(room.flamePosition);if(distance<.9){room.heat.value=Math.min(1,room.heat.value+dt/3);game.roomSave.heat=room.heat.value;if(room.heat.value>.97&&!has('heat')){puzzle.set('heat');show('The light remembers','Brown marks rise from the paper where the heat touched it.',[],true);sound('slide','candle','[The paper rustles above the candle]');}}}
    if(game.started&&game.viewId==='mural'&&has('lampOff')){moonTimer+=dt;if(moonTimer>2&&!has('moon')){puzzle.set('moon');show('A constellation awakens','Some stars hold their glow longer than the others. A shape waits among them.');}}else moonTimer=0;
    if(musicTime>=0){musicTime+=dt;const notes=[523.25,659.25,783.99,659.25,587.33,523.25];if(melody<notes.length&&musicTime>.4+melody*.35){audio.sound('bell',o.cage.position,'[A small music-box melody]',notes[melody++]);}if(chimes<7&&musicTime>3.2+chimes*.83){chimes++;audio.sound('bell',o.cage.position,`[Chimes: ${'• '.repeat(chimes).trim()}]`,1046.5);const start=o.bird.position.y;void motion.to(.55,t=>{o.bird.position.y=birdRest+Math.sin(t*Math.PI)*.11;o.bird.rotation.z=Math.sin(t*Math.PI)*.12;});}if(chimes===7&&musicTime>9.3){musicTime=-1;puzzle.set('bird');if(game.viewId==='cage'&&!game.inspector.active)show('The song falls quiet','The little bird settles. The final chimes linger in the room.',[button('wind','Listen again',true)]);}}
  }
  return {action,view,tick,restore,drag:(dx)=>{if(game.viewId==='painting'&&has('straight')&&!has('painting')&&Math.abs(dx)>4){void action('slide-painting');return true;}return false;}};
}
